### ISSUE TITLE
Floating Resource Icons

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/GGJ-2023#9]
Spawn particle effects of resources whenever the resources spawn for that producer.

Spawn a bunch of little icons using unity particle systems.

**Comment by ndamalas** [comment]
- Visual indication of resource collection from the plant/object itself
    - One for each type of resource
- Only visible to owner of plant

**Comment by ndamalas** [comment]
Ok, the oak tree now has 3 particle effect systems: one for water, one for sun, and one for seed

**Comment by ndamalas** [comment]
Next stop is copying them to other plants, then finding how to get them to trigger on resource collection

**Comment by ndamalas** [comment]
Now have been copied to sunflower and watermelon, next step is figuring out how to trigger on resource collection

**Comment by nicholas-maltbie** [comment]
Trigger on this function @ndamalas 

https://github.com/nicholas-maltbie/GGJ-2023/blob/7e44e17fc7c6b73e518a482d26253a4fa1e7af67/Assets/Scripts/Plants/Plant.cs#L106-L119

**Comment by ndamalas** [comment]
> 

Got it, thank you!

**Comment by ndamalas** [comment]
PR for this issue:
https://github.com/nicholas-maltbie/GGJ-2023/pull/22
